template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "udmu1245"
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
