template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "udmu1245"
__REPO__ = "lang-udm"
__UND2C__ = "udm"
__UNDEFINED__ = "Udmurt"
__UND__ = "udm"
