[package]
name = "udm"
human_name = "Udmurt"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.udm]
filename = "udm-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-udm"
platform = "windows"
uuid = "A20956EC-901B-4AC8-9CD3-D8897920B4E5"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.udm"
package = "speller-udm"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-udm-mso"
platform = "windows"
uuid = "4D7249A1-5B73-40A2-832C-FD79D62BF15E"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-udm"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
